[package]
name = "ned-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "ned"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.7", features = ["derive"] }
ned-core = { version = "0.6.1", path = "../ned-core" }
ned-daemon = { version = "0.6.1", path = "../ned-daemon" }

[dev-dependencies]
assert_cmd = "2.2.2"
insta = "1.48.0"
serde_json = "1.0.151"
tempfile = "3.27.0"
