[package]
name = "ned-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "ned"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.7", features = ["derive"] }
ned-core = { version = "0.1.0", path = "../ned-core" }

[dev-dependencies]
assert_cmd = "2.2.2"
insta = "1.48.0"
tempfile = "3.27.0"
