dark = false
added = "#50a14f"
removed = "#e45649"

[syntax]
keyword = "#a626a4"
string = "#50a14f"
"string.escape" = "#0184bc"
"text.literal" = "#50a14f"
comment = "#a0a1a7 italic"
function = "#4078f2"
"function.macro" = "#0184bc"
type = "#c18401"
constructor = "#c18401"
constant = "#986801"
number = "#986801"
boolean = "#986801"
escape = "#0184bc"
attribute = "#986801"
property = "#e45649"
label = "#e45649"
"variable.builtin" = "#c18401"
tag = "#e45649"
"text.title" = "#e45649 bold"
"text.uri" = "#4078f2 underline"
"text.reference" = "#4078f2"

[ui]
header = "bold"
line-number = "#9d9d9f"
kind = "#0184bc"
dim = "#a0a1a7"
hunk-header = "#0184bc"
error = "#e45649 bold"
warning = "#c18401 bold"
info = "#4078f2 bold"
note = "#0184bc bold"
