dark = true
added = "#98c379"
removed = "#e06c75"

[syntax]
keyword = "#c678dd"
string = "#98c379"
"string.escape" = "#56b6c2"
"text.literal" = "#98c379"
comment = "#7f848e italic"
function = "#61afef"
"function.macro" = "#56b6c2"
type = "#e5c07b"
constructor = "#e5c07b"
constant = "#d19a66"
number = "#d19a66"
boolean = "#d19a66"
escape = "#56b6c2"
attribute = "#d19a66"
property = "#e06c75"
label = "#e06c75"
"variable.builtin" = "#e5c07b"
tag = "#e06c75"
"text.title" = "#e06c75 bold"
"text.uri" = "#61afef underline"
"text.reference" = "#61afef"

[ui]
header = "bold"
line-number = "#636d83"
kind = "#56b6c2"
dim = "#636d83"
hunk-header = "#56b6c2"
error = "#e06c75 bold"
warning = "#e5c07b bold"
info = "#61afef bold"
note = "#56b6c2 bold"
